services: 
 
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysupersecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hackathon
 
volumes:
  pgdata: